import { useEffect, useMemo, useState } from 'react'
import { CreditCard, Receipt, Loader2 } from 'lucide-react'
import { jsPDF } from 'jspdf'
import { fetchBusinessesForAdmin } from '../services/businessOnboardingService'
import { createInvoice, fetchInvoices, markInvoicePaid, sendExpiryAlerts } from '../services/subscriptionService'
import './InvoicesPage.css'

function formatDate(value) {
  if (!value) return '—'
  try {
    return new Date(value).toLocaleString()
  } catch {
    return '—'
  }
}

function formatPlan(planCode) {
  const code = String(planCode || '').toLowerCase()
  if (!code) return '—'
  return code.charAt(0).toUpperCase() + code.slice(1)
}

function invoiceRef(row) {
  const idPart = String(row.id || '').replace(/-/g, '').slice(0, 10).toUpperCase()
  const timePart = row.created_at ? new Date(row.created_at).getTime().toString().slice(-6) : '000000'
  return `INV-${timePart}-${idPart || 'N/A'}`
}

const InvoicesPage = ({ userProfile }) => {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [rows, setRows] = useState([])
  const [businesses, setBusinesses] = useState([])
  const [form, setForm] = useState({
    business_id: '',
    plan_code: 'starter',
    amount_cents: '2900',
    currency: 'usd',
    notes: '',
  })
  const [submitting, setSubmitting] = useState(false)
  const [sendingReminders, setSendingReminders] = useState(false)
  const isSuperAdmin = String(userProfile?.role || '').toLowerCase() === 'super_admin'

  const loadInvoices = async () => {
    const data = await fetchInvoices()
    setRows(data || [])
  }

  useEffect(() => {
    let mounted = true
    ;(async () => {
      setLoading(true)
      setError('')
      try {
        const data = await fetchInvoices()
        if (!mounted) return
        setRows(data || [])
        if (isSuperAdmin) {
          const businessesData = await fetchBusinessesForAdmin()
          if (mounted) {
            setBusinesses(businessesData || [])
            if (!form.business_id && businessesData?.[0]?.id) {
              setForm((prev) => ({ ...prev, business_id: businessesData[0].id }))
            }
          }
        }
      } catch (err) {
        if (!mounted) return
        setError(err.message || 'Failed to load invoice history.')
      } finally {
        if (mounted) setLoading(false)
      }
    })()
    return () => { mounted = false }
  }, [isSuperAdmin])

  const stats = useMemo(() => {
    const total = rows.length
    const activeCount = rows.filter((r) => {
      const status = String(r.status || '').toLowerCase()
      return status === 'active' || status === 'paid'
    }).length
    const latest = rows[0]?.created_at || null
    return { total, activeCount, latest }
  }, [rows])

  const downloadInvoicePdf = (row) => {
    const doc = new jsPDF()
    const ref = invoiceRef(row)
    const plan = formatPlan(row.plan_code)
    const status = String(row.status || 'unknown')
    const purchasedOn = formatDate(row.created_at)
    const periodEnds = formatDate(row.due_at || row.ends_at)

    doc.setFontSize(18)
    doc.text('Invoice Receipt', 14, 20)

    doc.setFontSize(11)
    doc.text(`Invoice Ref: ${ref}`, 14, 34)
    doc.text(`Plan: ${plan}`, 14, 42)
    doc.text(`Status: ${status}`, 14, 50)
    doc.text(`Purchased On: ${purchasedOn}`, 14, 58)
    doc.text(`Period Ends: ${periodEnds}`, 14, 66)
    doc.text(`Amount: ${(row.currency || 'usd').toUpperCase()} ${((row.amount_cents || 0) / 100).toFixed(2)}`, 14, 74)

    doc.setFontSize(10)
    doc.text('Generated by CRM Leads', 14, 90)
    doc.save(`${ref}.pdf`)
  }

  const handleGenerateInvoice = async (e) => {
    e.preventDefault()
    setSubmitting(true)
    setError('')
    try {
      await createInvoice({
        business_id: form.business_id,
        plan_code: form.plan_code,
        amount_cents: Number(form.amount_cents),
        currency: form.currency,
        notes: form.notes,
      })
      await loadInvoices()
    } catch (err) {
      setError(err.message || 'Failed to generate invoice.')
    } finally {
      setSubmitting(false)
    }
  }

  const handleMarkPaid = async (invoiceId) => {
    try {
      await markInvoicePaid(invoiceId)
      await loadInvoices()
    } catch (err) {
      setError(err.message || 'Failed to mark invoice as paid.')
    }
  }

  const handleSendReminders = async () => {
    setSendingReminders(true)
    setError('')
    try {
      await sendExpiryAlerts(3)
    } catch (err) {
      setError(err.message || 'Failed to send expiry reminders.')
    } finally {
      setSendingReminders(false)
    }
  }

  return (
    <div className="invoices-page animate-fade-in">
      <div className="invoices-header">
        <h2><Receipt size={22} /> Invoices & Billing History</h2>
        <p>Track when each subscription was purchased and its billing state.</p>
      </div>

      {isSuperAdmin && (
        <form className="invoice-generate-card" onSubmit={handleGenerateInvoice}>
          <h3>Generate Invoice</h3>
          <div className="invoice-generate-grid">
            <select
              value={form.business_id}
              onChange={(e) => setForm((prev) => ({ ...prev, business_id: e.target.value }))}
              required
            >
              <option value="" disabled>Select business</option>
              {businesses.map((biz) => (
                <option key={biz.id} value={biz.id}>{biz.name || biz.id}</option>
              ))}
            </select>
            <select
              value={form.plan_code}
              onChange={(e) => setForm((prev) => ({ ...prev, plan_code: e.target.value }))}
            >
              <option value="starter">Starter</option>
              <option value="growth">Growth</option>
              <option value="pro">Pro</option>
              <option value="enterprise">Enterprise</option>
            </select>
            <input
              type="number"
              min="1"
              placeholder="Amount (cents)"
              value={form.amount_cents}
              onChange={(e) => setForm((prev) => ({ ...prev, amount_cents: e.target.value }))}
              required
            />
            <input
              type="text"
              placeholder="Currency (usd)"
              value={form.currency}
              onChange={(e) => setForm((prev) => ({ ...prev, currency: e.target.value.toLowerCase() }))}
            />
            <input
              type="text"
              placeholder="Notes (optional)"
              value={form.notes}
              onChange={(e) => setForm((prev) => ({ ...prev, notes: e.target.value }))}
            />
            <button type="submit" disabled={submitting}>
              {submitting ? 'Generating...' : 'Generate Invoice'}
            </button>
          </div>
          <button type="button" className="invoice-reminder-btn" disabled={sendingReminders} onClick={handleSendReminders}>
            {sendingReminders ? 'Sending Alerts...' : 'Send Expiry Alerts'}
          </button>
        </form>
      )}

      <div className="invoices-metrics">
        <div className="invoice-metric-card">
          <span className="invoice-metric-label">Total Records</span>
          <strong>{stats.total}</strong>
        </div>
        <div className="invoice-metric-card">
          <span className="invoice-metric-label">Active Purchases</span>
          <strong>{stats.activeCount}</strong>
        </div>
        <div className="invoice-metric-card">
          <span className="invoice-metric-label">Latest Purchase</span>
          <strong>{stats.latest ? new Date(stats.latest).toLocaleDateString() : '—'}</strong>
        </div>
      </div>

      {loading ? (
        <div className="invoices-loading">
          <Loader2 size={20} className="spinning" />
          <span>Loading invoices...</span>
        </div>
      ) : error ? (
        <div className="invoices-error">{error}</div>
      ) : rows.length === 0 ? (
        <div className="invoices-empty">
          <CreditCard size={26} />
          <p>No invoice records are available yet.</p>
        </div>
      ) : (
        <div className="invoices-table-wrap">
          <table className="invoices-table">
            <thead>
              <tr>
                <th>Invoice Ref</th>
                <th>Plan</th>
                <th>Status</th>
                <th>Created</th>
                <th>Due/Paid Date</th>
                <th>Amount</th>
                <th>Invoice PDF</th>
                {isSuperAdmin && <th>Actions</th>}
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id}>
                  <td className="mono">{invoiceRef(row)}</td>
                  <td>{formatPlan(row.plan_code)}</td>
                  <td>
                    <span className={`invoice-status status-${String(row.status || '').toLowerCase()}`}>
                      {String(row.status || 'unknown').replace('_', ' ')}
                    </span>
                  </td>
                  <td>{formatDate(row.created_at)}</td>
                  <td>{formatDate(row.paid_at || row.due_at)}</td>
                  <td className="mono">{(row.currency || 'usd').toUpperCase()} {((row.amount_cents || 0) / 100).toFixed(2)}</td>
                  <td>
                    <button
                      type="button"
                      className="invoice-download-btn"
                      onClick={() => downloadInvoicePdf(row)}
                    >
                      Download PDF
                    </button>
                  </td>
                  {isSuperAdmin && (
                    <td>
                      {String(row.status || '').toLowerCase() !== 'paid' ? (
                        <button type="button" className="invoice-download-btn" onClick={() => handleMarkPaid(row.id)}>
                          Mark Paid
                        </button>
                      ) : '—'}
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

export default InvoicesPage
